### ISSUE TITLE
笑死，懶得修ㄌ

### ISSUE THREAD

**Issue by gnehs** [EarlySpringCommitee/TLHCrawler#8]
![default](https://user-images.githubusercontent.com/16719720/40725307-a8aedff2-6455-11e8-8cfa-7cd7ef853dd0.png)

https://tlhc.gnehs.net/tlhc/post/MTMtMTAwMS01ODk4LTEucGhw
http://web.tlhc.ylc.edu.tw/files/13-1001-5898-1.php

**Comment by SnowFireWolf** [comment]
QQ棒棒勝好邊緣

**Comment by gnehs** [comment]
![default](https://user-images.githubusercontent.com/16719720/41804511-1e24d404-76ca-11e8-971c-736f382133d3.png)
ㄏ結果更慘，不過其他鳥東西修好ㄌ

**Comment by gnehs** [comment]
其他錯誤頁面
http://localhost:3000/tlhc/post/MTQtMTAwMS02OTM3LHIxNS0xLnBocA
http://localhost:3000/tlhc/post/MTQtMTAwMS02ODU1LHIxNS0xLnBocA
